### ISSUE TITLE
Conversion from onnx to nnet format

### ISSUE THREAD

**Issue by mforets** [JuliaReach/NeuralNetworkAnalysis.jl#7]
see: https://github.com/sisl/NNet

---

After installing the python package `onnx`, and downloading the github package NNet  the following works in my machine

```julia
import sys
sys.path.append('/home/mforets/Tools/NNet')
from NNet.python.nnet import *

from NNet.converters.onnx2nnet import onnx2nnet
from onnx import *

## Script showing how to run onnx2nnet
# Min and max values used to bound the inputs
inputMins  = [0.0,-3.141593,-3.141593,100.0,0.0]
inputMaxes = [60760.0,3.141593,3.141593,1200.0,1200.0]

# Mean and range values for normalizing the inputs and outputs. All outputs are normalized with the same value
means  = [1.9791091e+04,0.0,0.0,650.0,600.0,7.5188840201005975]
ranges = [60261.0,6.28318530718,6.28318530718,1100.0,1200.0,373.94992]

# ONNX file to convert to .nnet file
onnxFile = '/home/mforets/Tools/NNet/nnet/TestNetwork2.onnx'

# Convert the file
onnx2nnet(onnxFile, inputMins, inputMaxes, means, ranges)
```

**Comment by SebastianGuadalupe** [comment]
I'm having a problem loading the module NNet
```python
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-175acfe1d4a3> in <module>
      1 import sys
      2 sys.path.append('/home/sguadalupe/NNet')
----> 3 from NNet.python.nnet import *

ModuleNotFoundError: No module named 'NNet'
```

**Comment by mforets** [comment]
oh, i think the path line should be `sys.path.append('/home/sguadalupe')`

**Comment by SebastianGuadalupe** [comment]
We tried converting [this model](https://github.com/verivital/ARCH-2019/blob/master/Other/Benchmark%209/bigger_controller.onnx) but we keep getting [this error](https://github.com/sisl/NNet/blob/master/converters/onnx2nnet.py#L115), the models use a version of onnx that has an operator called "FC"(we know this using `onnx.load(onnxFile).graph.node[1].op_type`), [it looks like it is no longer supported](https://github.com/onnx/onnx/releases/tag/v1.2.1), we get the error because the converter does not support FC, it only supports "MatMul", "Add" and "ReLu"

**Comment by mforets** [comment]
Closing this as we have other means for the conversion.. we can eventually reopen in case we need to parse such files.
